name: Notify package update
on:
  schedule:
    # Every Monday at 8:00 AM JST (Previous day 23:00 UTC)
    - cron: '0 23 * * 0'
  workflow_dispatch: {}
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check package updates
        uses: ./.github/actions/package-update-check
        with:
          webhook-url: ${{ env.SLACK_WEBHOOK_URL }}
          target-dir: ${{ github.workspace }}
